---
title: Alex Baldwin
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  pages:
    title: Pages
    output: true
    permalink: /:path/
defaults:
  - scope:
      path: ""
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
  - scope:
      path: "_pages/raverobot"
    values:
      sitemap: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-postcss
  - jekyll-og-image
description: "Designer, developer, and entrepreneur sharing thoughts on product design, technology, and startup culture."
baseurl: ""
url: https://www.alexbaldwin.com
twitter:
  username: alexbaldwin
markdown: kramdown
permalink: "/:slug/"
postcss:
  cache: false
og_image:
  output_dir: "/assets/og"
  image: "/assets/images/alexbaldwin.jpg"
  canvas:
    background_color: "#FAFAFA"
  header:
    font_family: "GeistSans"
    color: "#44403C"
  content:
    font_family: "GeistSans"
    color: "#44403C"
  domain: "alexbaldwin.com"
