---
title: Alex Baldwin
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
plugins:
  - jekyll-seo-tag
  - jekyll-postcss
  - jekyll-og-image
description: 'Alex Baldwin, product designer based out of San Francisco. Designer
  of Console.fm, Latte, Retina Mac Apps, GRID, 500 Startup''s Dashboard.io, and many
  more fun projects.

'
baseurl: ''
url: https://alexbaldwin.com
twitter:
  username: alexbaldwin
markdown: kramdown
permalink: "/:slug/"
postcss:
  cache: false
og_image:
  output_dir: "/assets/og"
  image: "/assets/images/alexbaldwin.jpg"
  canvas:
    background_color: "#FAFAFA"
  header:
    font_family: "GeistSans"
    color: "#44403C"
  content:
    font_family: "GeistSans"
    color: "#44403C"
  domain: "alexbaldwin.com"
